config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', as: :root
  resources :currencies, only: %i(new create update)
  get 'admin', to: 'currencies#new'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
# frozen_string_literal: true

class Currency < ApplicationRecord
  validates_presence_of :value
  validate :date_check
  after_commit :publish_currency

  def self.current
    if where('"to" > ?', Time.zone.now).exists?
      last
    else
      new(value: current_currency)
    end
  end

  private

  def date_check
    if to.present? && to < Time.zone.now
      errors.add(:to, 'Cannot setup value in the past')
    end
  end

  def publish_currency
    ActionCable.server.broadcast(
      'currencies',
      ApplicationController.render(
        partial: 'currencies/currency',
        locals: { currency: self }
      )
    )
  end

  def self.current_currency
    CurrencyParserService.new.result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def new
    @currency = Currency.last || Currency.new
  end

  def create
    @currency = Currency.new(currency_params)
    respond_to do |format|
      format.js do
        if @currency.save
          flash.now[:notice] = 'Currency succesfuly saved!'
          render :saved, layout: false
        else
          render :error, layout: false
        end
      end
    end
  end

  def update
    @currency = Currency.find(params[:id])
    respond_to do |format|
      format.js do
        if @currency.update(currency_params)
          flash.now[:notice] = 'Currency succesfuly saved!'
          render :saved, layout: false
        else
          render :error, layout: false
        end
      end
    end
  end

  private

  def currency_params
    params.require(:currency).permit(:value, :to)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/currencies/_currency.slim
#currency
  span = '%.2f RUB/USD' % currency.value

app/views/currencies/_form.slim
= form_for @currency, remote: true do |f|
  = render "shared/errors", resource: @currency

  .form-group
    = f.label :value
    = f.number_field :value, step: "0.01", class: 'form-control currency', data: { "number-to-fixed" => "2", "number-stepfactor" => "100" }
  .form-group
    = f.label :to
    = f.datetime_select :to, class: 'form-control'
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/currencies/error.js.erb
$("form").replaceWith("<%=j render 'form' %>")

app/views/currencies/new.slim
.card
  .card-header
    h3 New currency setup
  .card-body
    = render "form"

app/views/currencies/saved.js.erb
$("div.alert").remove();
$("form").prepend("<%=j render 'shared/notifications' %>")

app/views/home/index.slim
h2 Page for check current currency

app/views/layouts/application.slim
doctype html
html
  head
    title
      | UsdChecker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "shared/nav"
    .container.mt-4
      .row
        .col-md-9
          = render "shared/notifications"
          = yield
        .col-md-3
          .currency
            = render Currency.current
      hr
      =render 'shared/footer'

    = console if Rails.env.development?

app/views/shared/_errors.slim
-if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do
    =  "Errors: #{resource.errors.count}"
    - resource.errors.full_messages.each do |message|
      div class="alert alert-danger" = message

app/views/shared/_footer.slim
footer
  p © 2018 Karpinsky Stanislav

app/views/shared/_nav.slim
.container-fluid.navbar-menu
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .col-md-10
      .ul.navbar-nav.mr-auto
        li class="nav-item"
          = link_to "HOME", root_path, class: "nav-link"
        li class="nav-item"
          = link_to "Admin", admin_path, class: "nav-link"

app/views/shared/_notifications.slim
- flash.each do |key, value|
  div class="alert alert-dismissible alert-#{key == 'notice' ? 'success' : 'danger'}"
    = value